Repository chakra-ui/chakra-ui-docs, pull requests merged in 2022-05, with the labels that each got.

#458 docs(button): Update ButtonGroup example
  pages/docs/components/form/button.mdx
Labels: documentation, After next release, v2

#567 docs: add v1 backlink
  README.md
  src/components/version-switcher.tsx
Labels: v2

#569 docs: add migration guide for v2
  configs/guides-sidebar.json
  pages/guides/migration.mdx
Labels: v2

#577 chore: update dependencies for react 18
  README.md
  configs/components-sidebar.ts
  configs/sandpack-contents/formik-examples/login-form.js
  configs/sandpack-contents/formik-examples/validation.js
  configs/styled-system-sidebar.json
  contentlayer.config.ts
  next.config.js
  package.json
  pages/blog/[...slug].tsx
  pages/changelog/index.tsx
  pages/docs/[[...slug]].tsx
  pages/docs/components/disclosure/tabs.mdx
  pages/docs/components/layout/box.mdx
  pages/docs/components/overlay/popover.mdx
  pages/docs/components/overview.tsx
  pages/docs/components/recipes/as-prop.mdx
  pages/docs/components/typography/heading.mdx
  pages/docs/components/typography/text.mdx
  pages/docs/styled-system/features/color-mode.mdx
  pages/docs/styled-system/features/style-props.mdx
  pages/docs/styled-system/overview.mdx
  pages/faq/[[...slug]].tsx
  pages/guides/[[...slug]].tsx
  pages/guides/getting-started/vite-guide.mdx
  pages/guides/integrations/with-hook-form.mdx
  pages/tutorial/[[...slug]].tsx
  src/components/color-palette.tsx
  src/components/edit-page-button.tsx
  src/components/footer.tsx
  src/components/hackathon/index.tsx
  src/components/mdx-components/codeblock/codeblock.tsx
  src/components/props-table.tsx
  src/components/showcase/mask.tsx
  src/components/showcase/showcase-grid-item.tsx
  src/components/sidebar/sidebar-category.tsx
  src/components/sidebar/sidebar.tsx
  src/components/tutorial/tutorial-code-block.tsx
  src/components/tutorial/tutorial-container.tsx
  tsconfig.json
  yarn.lock
Labels: v2, merge before dependabot
